apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd-deployment
  labels:
    app: argo-cd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-cd
  template:
    metadata:
      labels:
        app: argo-cd
    spec:
      containers:
      - name: argo-cd
        image: gopal703/argo-cd:7
        ports:
        - containerPort: 80
